# Generated by Django 5.2.18 on 2026-10-07 18:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("fluxos", "0001_fluxo_inicial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Execucao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("fluxo_nome", models.CharField(max_length=120, verbose_name="nome do fluxo")),
                ("grafo_snapshot", models.JSONField(default=dict, verbose_name="grafo (snapshot)")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("executando", "Executando"),
                            ("sucesso", "Sucesso"),
                            ("erro", "Erro"),
                        ],
                        default="executando",
                        max_length=12,
                        verbose_name="status",
                    ),
                ),
                (
                    "iniciada_em",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, verbose_name="iniciada em"
                    ),
                ),
                (
                    "finalizada_em",
                    models.DateTimeField(blank=True, null=True, verbose_name="finalizada em"),
                ),
                ("erro_resumo", models.TextField(blank=True, verbose_name="resumo do erro")),
                (
                    "executado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="execucoes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="executado por",
                    ),
                ),
                (
                    "fluxo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execucoes",
                        to="fluxos.fluxo",
                        verbose_name="fluxo",
                    ),
                ),
            ],
            options={
                "verbose_name": "execução",
                "verbose_name_plural": "execuções",
                "ordering": ["-iniciada_em", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="ExecucaoNo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("no_id", models.CharField(max_length=40, verbose_name="id do nó")),
                ("no_tipo", models.CharField(max_length=20, verbose_name="tipo do nó")),
                (
                    "no_titulo",
                    models.CharField(blank=True, max_length=80, verbose_name="título do nó"),
                ),
                ("ordem", models.PositiveIntegerField(verbose_name="ordem")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sucesso", "Sucesso"),
                            ("erro", "Erro"),
                            ("nao_executado", "Não executado"),
                        ],
                        max_length=14,
                        verbose_name="status",
                    ),
                ),
                ("entrada", models.JSONField(default=dict, verbose_name="entrada")),
                ("saida", models.JSONField(default=dict, verbose_name="saída")),
                (
                    "erro_categoria",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="categoria do erro"
                    ),
                ),
                ("erro_mensagem", models.TextField(blank=True, verbose_name="mensagem do erro")),
                ("duracao_ms", models.PositiveIntegerField(default=0, verbose_name="duração (ms)")),
                (
                    "execucao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nos",
                        to="execucoes.execucao",
                    ),
                ),
            ],
            options={
                "verbose_name": "execução de nó",
                "verbose_name_plural": "execuções de nós",
                "ordering": ["execucao", "ordem"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("execucao", "ordem"), name="execucaono_ordem_unica"
                    )
                ],
            },
        ),
    ]
