# Generated by Django 5.2.18 on 2026-10-08 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contas", "0003_setor_usuario_setor"),
        ("execucoes", "0001_execucao_e_execucaono"),
        ("fluxos", "0002_fluxo_setor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="execucao",
            name="setor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="execucoes",
                to="contas.setor",
                verbose_name="setor",
            ),
        ),
        migrations.AddIndex(
            model_name="execucao",
            index=models.Index(fields=["setor", "iniciada_em"], name="exec_setor_inicio_idx"),
        ),
        migrations.AddIndex(
            model_name="execucao",
            index=models.Index(fields=["status", "iniciada_em"], name="exec_status_inicio_idx"),
        ),
    ]
