# Generated by Django 5.2.18 on 2026-10-07 14:30

import apps.fluxos.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fluxo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=120, verbose_name="nome")),
                (
                    "descricao",
                    models.TextField(blank=True, max_length=1000, verbose_name="descrição"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("rascunho", "Rascunho"), ("ativo", "Ativo")],
                        default="rascunho",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "grafo",
                    models.JSONField(
                        default=apps.fluxos.models.grafo_inicial, verbose_name="grafo"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em"),
                ),
                (
                    "dono",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fluxos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="dono",
                    ),
                ),
            ],
            options={
                "verbose_name": "fluxo",
                "verbose_name_plural": "fluxos",
                "ordering": ["-atualizado_em", "-pk"],
            },
        ),
    ]
