# Generated by Django 5.2.18 on 2026-10-08 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contas", "0003_setor_usuario_setor"),
        ("fluxos", "0001_fluxo_inicial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fluxo",
            name="setor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fluxos",
                to="contas.setor",
                verbose_name="setor",
            ),
        ),
    ]
