# Generated by Django 5.2.18 on 2026-10-08 20:32

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contas", "0002_grupos_dos_papeis"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=80, verbose_name="nome")),
                ("ativo", models.BooleanField(default=True, verbose_name="ativo")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
            ],
            options={
                "verbose_name": "setor",
                "verbose_name_plural": "setores",
                "ordering": ["nome"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("nome"), name="setor_nome_unico_ci"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="usuario",
            name="setor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarios",
                to="contas.setor",
                verbose_name="setor",
            ),
        ),
    ]
